
name: Waka Readme

on:
  schedule: # 00:30 UTC
    - cron: '30 0 1/5 * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_EMAIL: "11565373+bysomeone@users.noreply.github.com"
          SYMBOL_VERSION: 2
